name: "Setup Browser Action"
description: "A GitHub Action to setup Node.js, yarn environment, and browsers for testing."

runs:
  using: "composite"
  steps:
    - name: Browser Cache
      id: browser-cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-playwright-

    - name: Install Playwright browsers
      if: steps.browser-cache.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps
      shell: bash
